### PR TITLE
Adding support of UWP apps

### PR DESCRIPTION
**Pull request by mathieumack**
Adding support of UWP apps.
nuspec is changed to support the Platform.

### CODE REVIEW

**Comment by azchohfi** [comment]
Awesome!
I think .vs should be added to gitignore...

**Comment by mathieumack** [comment]
Thanks.
For the git ignore, I'm not "git" fluent. Is there a solution to remove these files from the last commit properly ?

**Comment by azchohfi** [comment]
Yes, you _can_, but It's not simple...
You need to use this commands (I'll explain them):
_git reset HEAD~1_
This will rewind the HEAD of your branch to HEAD-1 commit, so it will basically delete your commit, but you won't loose it, relax. It will be on your staging area. All you have to do is commit everything else once again (using the same description, if you like) and push it again to your branch. How did you commit last time? _git add ._ then _git commti -m "......"_? If so, you can't add "."(which means _all_). Since there are so many files, use any git cliente to help you selectingthe commit files, or add them manually. It's not easy... Sorry...
You need to force the push, because the remote (on GitHub) already has this last commit, so you need to override that. You do so by using a _-force_ on your push command, like this:
_git push -force_
The PullRequest(PR) will be automatically updated.

**Comment by azchohfi** [comment]
Actually, don't use the description "v1.0". Use something more meaningful, like.... "Added support for UWP."

**Comment by mathieumack** [comment]
Ok, I will try this manipulation and check my comments.
Thank you !

**Comment by azchohfi** [comment]
You could have just updated the same Pull Request, without closing it, but that's ok.
If you've pushed more commits into your branch, it would have updated this PR.

**Comment by mathieumack** [comment]
The pull requets ended automatically after the reset HEAD command (or a manual push after the reset perhaps ... I will learn more git command lines to be more efficient in next times.
Thanks for your help.

**Comment by azchohfi** [comment]
Ohhh, kinda makes sense... Great!

**Pull request closed without merging**
